[build]
publish = "docs/build"
command = "make netlify"
ignore = "./build/docs-build-needed.sh"
edge_functions = "docs/functions"

[build.environment]
NODE_VERSION = "22.15.0"

[[edge_functions]]
# this path should not be changed as various external sites depend on it for OPA
# badges.
path = "/badge-endpoint/*"
function = "badge"

[[edge_functions]]
# this path should not be changed as various external sites depend on it for OPA
# badges.
path = "/badge/*"
function = "badge"

# Redirect all path based versioned requests to their new archived sites.
# https://github.com/open-policy-agent/opa/issues/7037
[[edge_functions]]
path = "/docs/*"
function = "version-redirect"
