[build]
publish = "docs/website/public"
command = "make docs-production-build"

[build.environment]
HUGO_VERSION = "0.55.5"

[context.deploy-preview]
command = "make docs-preview-build"

[context.branch-deploy]
command = "make docs-preview-build"

[dev]
# "netlify dev" will serve the static content using netlify locally
# with all the redirects and other netlify specific rules in place.
publish = "docs/website/public"

# To run the netlify dev service with hugo dev server "live" behind 
# it uncomment these lines:
#command = "make docs-hugo-serve"
#port = 1313
