[build]
publish = "docs/website/public"
command = "make netlify-prod WASM_ENABLED=0 CGO_ENABLED=0"
ignore = "./build/docs-build-needed.sh"
edge_functions = "docs/website/edge"

[[edge_functions]]
path = "/badge-endpoint/*"
function = "badge"

[build.environment]
# keep this version in sync with the version in .github/workflows/pull-request.yml
HUGO_VERSION = "0.113.0"

[context.deploy-preview]
command = "make netlify-preview WASM_ENABLED=0 CGO_ENABLED=0"

[context.branch-deploy]
command = "make netlify-preview WASM_ENABLED=0 CGO_ENABLED=0"

[dev]
# "netlify dev" will serve the static content using netlify locally
# with all the redirects and other netlify specific rules in place.
publish = "docs/website/public"
framework = "#static"

# To run the netlify dev service with hugo dev server "live" behind
# it uncomment these lines:
#command = "make docs-hugo-serve"
#port = 1313
