title = "Open Policy Agent"
baseURL = "https://openpolicyagent.org"
languageCode = "en"
disableKinds = ["taxonomy", "taxonomyTerm"]
googleAnalytics = "UA-84550302-1"

pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsStyle = "tango"
pygmentsGuessSyntax = true

# Don't try and render the code snippets as html pages
# the are loaded via shortcode helpers.
ignorefiles = [ "/docs/v.*/code/.*" ]

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
description = "Policy-based control for cloud native environments"
tagline = "Empower your administrators with flexible, fine-grained control across your entire stack."
algolia_api_key = "26fa0633923a7cb9432cf2851b77dca6"

[params.social]
twitter = "OpenPolicyAgent"
medium = "https://blog.openpolicyagent.org"
slack = "https://slack.openpolicyagent.org"
github = "https://github.com/open-policy-agent/opa"

[params.logos]
sidebar = "/img/logos/opa-horizontal-color.png"
navbar = "/img/logos/opa-icon-white.png"

[params.ui]
[params.ui.feedback]
# Requires googleAnalytics to be set to track feedback events
# Set hide_feedback: true in a page's front matter to disable feedback for that page
enable = true

[menu]
[[menu.social]]
name = "Medium"
url = "https://blog.openpolicyagent.org"
weight = 1

[[menu.social]]
name = "Twitter"
url = "https://twitter.com/openpolicyagent"
weight = 2

[[menu.social]]
name = "Slack"
url = "https://slack.openpolicyagent.org/"
weight = 3

[[menu.social]]
name = "GitHub"
url = "https://github.com/open-policy-agent/opa"
weight = 4

[mediaTypes."text/netlify"]
delimiter = ""

[outputFormats.REDIRECTS]
mediaType = "text/netlify"
baseName = "_redirects"

[outputs]
home = ["HTML", "REDIRECTS"]
