title = "Open Policy Agent"
baseURL = "https://www.openpolicyagent.org"
languageCode = "en"
disableKinds = ["taxonomy", "taxonomyTerm"]

pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsStyle = "tango"
pygmentsGuessSyntax = true

# Don't try and render the code snippets as html pages
# the are loaded via shortcode helpers.
ignorefiles = [ "/docs/v.*/code/.*" ]

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
description = "Policy-based control for cloud native environments"
tagline = "Empower your administrators with flexible, fine-grained control across your entire stack."
algolia_api_key = "40a3909859478f0b23c385214feab2ef"
GithubEdit = "https://github.com/open-policy-agent/opa/edit/main/docs/content/"

[params.social]
twitter = "OpenPolicyAgent"
medium = "https://blog.openpolicyagent.org"
slack = "https://slack.openpolicyagent.org"
github = "https://github.com/open-policy-agent/opa"
discussions = "https://github.com/open-policy-agent/feedback/discussions"

[params.logos]
sidebar = "/img/logos/opa-horizontal-color.png"
navbar = "/img/logos/opa-icon-white.png"

[params.ui]
[params.ui.feedback]
# Requires Google Analytics to be enabled for the site.
# Set hide_feedback: true in a page's front matter to disable feedback for that page
enable = true

[mediaTypes."text/netlify"]
delimiter = ""

[outputFormats.REDIRECTS]
mediaType = "text/netlify"
baseName = "_redirects"

[outputs]
home = ["HTML", "REDIRECTS"]
