# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Open Policy Agent
email:
description: >
  OPA: An open source project to policy enable any application.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://openpolicyagent.org" # the base hostname & protocol for your site
github_username:  open-policy-agent
github_repo: opa

# Build settings
markdown: kramdown
