name: Nightly
on:
  schedule:
    - cron:  '0 8 * * *'  # Daily, at 8:00 UTC

jobs:
  race-detector:
    name: Go Race Detector
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Test with Race Detector
        run: CGO_ENABLED=1 make ci-go-race-detector

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2.1.0
        if: ${{ failure() && secrets.SLACK_NOTIFICATION_WEBHOOK != "" }}
        env:
          SLACK_COLOR: '#FF0000'
          SLACK_ICON_EMOJI: ':x:'
          SLACK_MESSAGE: 'OPA Race Detector Test Failure!'
          SLACK_USERNAME: Github Actions
          SLACK_WEBHOOK: ${{ secrets.SLACK_NOTIFICATION_WEBHOOK }}
          SLACK_FOOTER: 'Github Action Slack Notification'

  fuzzer:
    name: Go Fuzzer
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run go-fuzz
        run: make ci-go-check-fuzz

      - name: Upload Workdir
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: workdir
          path: ./build/fuzzer/workdir

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2.1.0
        if: ${{ failure() && secrets.SLACK_NOTIFICATION_WEBHOOK != "" }}
        env:
          SLACK_COLOR: '#FF0000'
          SLACK_ICON_EMOJI: ':x:'
          SLACK_MESSAGE: 'OPA Fuzzer Test Failure!'
          SLACK_USERNAME: Github Actions
          SLACK_WEBHOOK: ${{ secrets.SLACK_NOTIFICATION_WEBHOOK }}
          SLACK_FOOTER: 'Github Action Slack Notification'
